/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptomasters;

import static cryptomasters.PickDownloadFileGUI.request;
import java.io.File;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author kdonahoe
 */
public class DownloadFileGUIOld extends javax.swing.JPanel {
    public static RequestData request;
    /**
     * Creates new form DownloadFileGUI
     */
    public DownloadFileGUIOld(RequestData request) {
        DownloadFileGUIOld.request = request;
        initComponents();
        System.out.println("Entered DownloadFileGui");
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directoryButtonGroup = new javax.swing.ButtonGroup();
        fileNameInput = new javax.swing.JTextField();
        headerLabel = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        existingDirectoryRadioButton = new javax.swing.JRadioButton();
        newDirectoryRadioButton = new javax.swing.JRadioButton();
        submitDownloadButton = new javax.swing.JButton();
        newDirectoryNameInput = new javax.swing.JTextField();
        chooseDirectory = new javax.swing.JFileChooser();

        fileNameInput.setText("file.txt");
        fileNameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileNameInputMouseClicked(evt);
            }
        });

        headerLabel.setText("Name your file and select a directory on your computer to save it to!");
        headerLabel.setToolTipText("");

        fileLabel.setText("File name:");

        directoryButtonGroup.add(existingDirectoryRadioButton);
        existingDirectoryRadioButton.setText("Download to existing directory");
        existingDirectoryRadioButton.setName(""); // NOI18N
        existingDirectoryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingDirectoryRadioButtonActionPerformed(evt);
            }
        });

        directoryButtonGroup.add(newDirectoryRadioButton);
        newDirectoryRadioButton.setSelected(true);
        newDirectoryRadioButton.setText("Create a new directory");
        newDirectoryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDirectoryRadioButtonActionPerformed(evt);
            }
        });

        submitDownloadButton.setText("Download dat man");
        submitDownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDownloadButtonActionPerformed(evt);
            }
        });

        newDirectoryNameInput.setText("Enter new directory name");
        newDirectoryNameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newDirectoryNameInputMousePressed(evt);
            }
        });

        chooseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(fileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(submitDownloadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDirectoryRadioButton)
                            .addComponent(newDirectoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chooseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(existingDirectoryRadioButton)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newDirectoryRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDirectoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(existingDirectoryRadioButton)
                .addGap(18, 18, 18)
                .addComponent(chooseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(submitDownloadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedButtonText(ButtonGroup buttonGroup){
        for(Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if(button.isSelected()){
                return button.getText();
            }
        }
        return null;
    }
    
    
    
    
    private void existingDirectoryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingDirectoryRadioButtonActionPerformed
        // TODO add your handling code here:
         System.out.println("entered existing Directory Radio button action");
        newDirectoryNameInput.setVisible(false);
        chooseDirectory.setVisible(true);
        revalidate();
    }//GEN-LAST:event_existingDirectoryRadioButtonActionPerformed

    private void newDirectoryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDirectoryRadioButtonActionPerformed
        // TODO add your handling code here:
        newDirectoryNameInput.setVisible(true);
        chooseDirectory.setVisible(false);
        System.out.println("entered new Directory Radio button action");
        revalidate();
    }//GEN-LAST:event_newDirectoryRadioButtonActionPerformed

    private void submitDownloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDownloadButtonActionPerformed
        // TODO add your handling code here:

        if(fileNameInput.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please provide file name");
        }
        else{
            String directoryChoice = getSelectedButtonText(directoryButtonGroup);
        if(directoryChoice == null){
            JOptionPane.showMessageDialog(this, "Please select a radio option!");
        }
        if(directoryChoice.equals("Create a new directory")){
            if(newDirectoryNameInput.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please provide new directory name");
            }
            
            String downloadFileSaveName = fileNameInput.getText();
            request.setDownloadFileSaveName(downloadFileSaveName);
            String newDirectoryName = newDirectoryNameInput.getText();
            
            //FOR NOW, automatically saves new directory on my Desktop (have to change so not just me)
            request.setDownloadDirectory("/Users/kdonahoe/Desktop/"+newDirectoryName);
            
            try{
                HttpsDownload downloadIt = new HttpsDownload(request);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Wrong credentials supplied!");
            }
            
        }
        else if(directoryChoice.equals("Download to existing directory")){
            if(request.getDownloadFileSaveName() == null){
                   JOptionPane.showMessageDialog(this, "Please select directory");
               }
            else{
                try{
                    HttpsDownload downloadIt = new HttpsDownload(request);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Wrong credentials supplied!");
                }   
            }
        }
        }
    }//GEN-LAST:event_submitDownloadButtonActionPerformed

    private void chooseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDirectoryActionPerformed
        // TODO add your handling code here:
          System.out.println("entered new Directory Radio button action");

        String command = evt.getActionCommand();
        if(command.equals(javax.swing.JFileChooser.APPROVE_SELECTION)){
            File selectedFile = chooseDirectory.getSelectedFile();
            
            String absolutePath = selectedFile.getAbsolutePath();
            request.setDownloadFileSaveName(absolutePath);
        
            System.out.println("Will download file to: "+request.getDownloadFileSaveName());

        }
        else if(command.equals(javax.swing.JFileChooser.CANCEL_OPTION)){
            JOptionPane.showMessageDialog(this, "Please either select existing directory, or create a new one.");
        }

    }//GEN-LAST:event_chooseDirectoryActionPerformed

    private void fileNameInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameInputMouseClicked
        // TODO add your handling code here:
        fileNameInput.setText("");
    }//GEN-LAST:event_fileNameInputMouseClicked

    private void newDirectoryNameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDirectoryNameInputMousePressed
        // TODO add your handling code here:
        newDirectoryNameInput.setText("");
    }//GEN-LAST:event_newDirectoryNameInputMousePressed

    
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickDownloadFileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickDownloadFileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickDownloadFileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickDownloadFileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("ENTERED MAIN of DownloadFileGUI");
                new DownloadFileGUIOld(request).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooseDirectory;
    private javax.swing.ButtonGroup directoryButtonGroup;
    private javax.swing.JRadioButton existingDirectoryRadioButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileNameInput;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField newDirectoryNameInput;
    private javax.swing.JRadioButton newDirectoryRadioButton;
    private javax.swing.JButton submitDownloadButton;
    // End of variables declaration//GEN-END:variables
}
